source 'https://rubygems.org'

# Specify your gem's dependencies in orchard.gemspec
gemspec

#Added by Marcel
gem "mongo"
gem "mongoid"
gem 'sunspot_mongoid'
gem 'sunspot_solr'
gem 'will_paginate_mongoid'
gem 'activerecord'

gem 'sqlite3'